### PR TITLE
fix: avoid duplicated entries

### LINKED ISSUE #11: deduplicate entries
> ```tsv
> k8s.io/kops	d8ce157d81e704dfdac0412fcb2b0de74553952d	https://github.com/kubernetes/kops	18757
> k8s.io/kops	d8ce157d81e704dfdac0412fcb2b0de74553952d	https://github.com/kubernetes/kops	18757
> ```

On commit https://github.com/mvdan/corpus/commit/1ae32d9009c32dcf3f6759e4c0f8fdc370f4d518 there is a duplicate entry.

### PR DESCRIPTION
**Pull request by gqgs**
Resolves #11

### CODE REVIEW

**Review by mvdan — APPROVED** [review]
Thanks!

**Comment by mvdan** [comment]
Not sure why, but the workflow seems to have broken in master just a few days ago.

**Comment by gqgs** [comment]
@mvdan `DefaultBranchRef.Target.Commit.PushedDate` is coming back empty.
Noticed this in the [docs](https://docs.github.com/en/graphql/reference/objects#commit):

>Deprecation notice pushedDate is deprecated. pushedDate is no longer supported. Removal on 2023-07-01 UTC.
 
So it seems we need a new field now. I can update here to use `committedDate` instead or open a new PR for that.

**Comment by gqgs** [comment]
@mvdan Pushed a new commit here to replace the deprecated field and fix the workflow.

**Comment by mvdan** [comment]
Nicely spotted, it works now :) Weird that GitHub are breaking the API without any versioning whatsoever. I would probably avoid GraphQL if I were to write this code again.

**Pull request merged**
